# when using the default proxy server port
local_backend: true

publish_mode: editorial_workflow

backend:
  name: git-gateway
  repo: AurelienDesplanque/cap4training # Path to your GitHub repository
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

media_folder: public/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Creation Date', name: 'created_at', widget: 'datetime', required: false }
      - { label: 'Updated Date', name: 'updated_at', widget: 'datetime', required: false }
      - { label: 'Short Description', name: 'short_description', widget: 'text', required: false }
      - { label: 'Long Description', name: 'long_description', widget: 'markdown', required: false }
      - { label: 'Picture blog', name: 'featured_image', widget: 'image', required: false}
      - { label: 'Training', name: 'training', widget: 'relation', collection: 'training', value_field: 'title', search_fields: ['title']}


collections:
  - name: 'training'
    label: 'Training'
    folder: 'content/training'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}




